id: jeecg-boot-swagger
info:
  name: Jeecg Boot Swagger Bootstrap UI - Detect
  author: ritikchaddha
  severity: info
  description: 'The "Jeecg Boot Swagger Bootstrap UI - Detect" vulnerability allows
    an attacker to access the Swagger UI interface, which provides detailed information
    about the application''s API endpoints, request and response structures, and other
    sensitive details. This exposes the application to several security risks, as
    the attacker can potentially exploit vulnerabilities in the API endpoints, perform
    unauthorized actions, gather intelligence for more targeted attacks, and discover
    additional vulnerabilities in the application or related components.


    The Swagger UI is designed to provide a user-friendly interface for developers
    to explore and interact with the application''s APIs. However, leaving the Swagger
    UI accessible in a production environment can inadvertently reveal sensitive information
    and increase the attack surface. Attackers can leverage the Swagger UI to gain
    a deeper understanding of the application''s functionality and potentially find
    and exploit vulnerabilities, leading to unauthorized access, data disclosure,
    or even remote code execution.


    To mitigate this vulnerability, it is recommended to either disable the Swagger
    UI in the production environment or implement strict access controls, such as
    authentication and authorization mechanisms, to limit access to authorized users
    or IP addresses. Additionally, the API documentation and endpoints exposed through
    the Swagger UI should be regularly reviewed and updated to remove or restrict
    any unnecessary or sensitive information. Implementing other security measures,
    such as rate-limiting or additional security controls, can further reduce the
    risk of automated attacks or brute-force attempts against the Swagger UI and API
    endpoints.'
  classification:
    cpe: cpe:2.3:a:jeecg:jeecg-boot:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: jeecg
    product: jeecg-boot
    shodan-query: title:"Jeecg-Boot"
    fofa-query: "title=\"JeecgBoot \u4F01\u4E1A\u7EA7\u4F4E\u4EE3\u7801\u5E73\u53F0\
      \""
  tags: jeecg,swagger,detect,exposure
  impact: '- Attacker can access the Swagger UI interface, which provides detailed
    information about the API endpoints, request/response structures, and other sensitive
    details.

    - Attacker can exploit vulnerabilities in the API endpoints, potentially leading
    to unauthorized access, data disclosure, or even remote code execution.

    - Attacker can use the Swagger UI to perform unauthorized actions, such as modifying
    or deleting data, based on the permissions and functionality exposed through the
    API.

    - Attacker can use the information gathered from the Swagger UI to craft more
    targeted attacks, such as credential guessing or method tampering, against the
    application.

    - Attacker can potentially discover and exploit other vulnerabilities in the application
    or related components through the information provided in the Swagger UI.'
  remediation: 'To address the "Jeecg Boot Swagger Bootstrap UI - Detect" vulnerability,
    the Swagger UI interface should be secured or disabled. This can be achieved by
    restricting access to the Swagger UI or by configuring the application to only
    expose the necessary API documentation. By taking these measures, you can reduce
    the risk of unauthorized access, data disclosure, and potential exploitation of
    vulnerabilities.


    - Disable the Swagger UI in the production environment, unless it is required
    for legitimate purposes. If it is necessary to keep the Swagger UI, ensure that
    access to it is restricted to authorized users or IP addresses.

    - Implement authentication and authorization mechanisms to control access to the
    Swagger UI and the underlying API endpoints.

    - Review the API documentation and endpoints exposed through the Swagger UI, and
    remove or restrict access to any sensitive or unnecessary information.

    - Regularly review and update the Swagger UI configuration to ensure that it aligns
    with the application''s security requirements and does not expose unnecessary
    information.

    - Consider implementing rate-limiting or other security controls to mitigate the
    risk of automated attacks or brute-force attempts against the Swagger UI and API
    endpoints.'
http:
- method: GET
  path:
  - '{{BaseURL}}/jeecg-boot/'
  matchers:
  - type: word
    part: body
    words:
    - <title>Swagger-Bootstrap-UI</title>
